from hex import HexState, Hex

# A hex has six neighbours given as offsets from a central axial coordinate
HEX_DIRECTIONS = [
    (1, 0),
    (1, -1),
    (0, -1),
    (-1, 0),
    (-1, 1),
    (0, 1),
]
# A 9x9 hex map extends 4 hexes out from an origin hex
HEX_RANGE = 4


# A hex map is a contiguous arrangement of connected hexes
class Map:
    # Create the hex map
    def __init__(self, canvas):
        self.canvas = canvas
        self.debug = False
        # The start and end hexes for a potential route through the hex map
        self.start_hex = None
        self.end_hex = None
        self.hexes = {}
        # Create the hexes in the hex map. Nudge the hexes so they form a rough square
        for r in range(-HEX_RANGE, HEX_RANGE + 1):
            for q in range(-HEX_RANGE, HEX_RANGE + 1):
                axial_coord = (q + -(r // 2), r)
                self.hexes[axial_coord] = Hex(
                    canvas, axial_coord, self.on_start, self.on_end, self.on_clear, self.on_debug, self.on_barrier)

    # Calculate the route through the hex map
    def update_route(self):
        # Wipe the previously drawn route
        for hex in self.hexes.values():
            if hex.state == HexState.EMPTY:
                hex.set_colour_from_state()
            hex.set_text("")
        # Calculate the route and indicate it on the hex map
        if self.start_hex and self.end_hex:
            route = self.a_star()
            for hex in route:
                if not hex == self.start_hex and not hex == self.end_hex:
                    self.canvas.itemconfig(hex.polygon, fill="orange")

    # Callback when a barrier in the hex map is changed
    def on_barrier(self):
        self.update_route()

    # Callback when the start hex in the hex map is changed
    def on_start(self, hex):
        if hex.state == HexState.EMPTY:
            if self.start_hex:
                self.start_hex.set_state(HexState.EMPTY)
            hex.set_state(HexState.START)
            self.start_hex = hex
            self.update_route()

    # Callback when the end hex is the hex map is changed
    def on_end(self, hex):
        if hex.state == HexState.EMPTY:
            if self.end_hex:
                self.end_hex.set_state(HexState.EMPTY)
            hex.set_state(HexState.END)
            self.end_hex = hex
            self.update_route()

    # Callback when either the start or end hex is cleared
    def on_clear(self, hex):
        if hex.state == HexState.START:
            hex.set_state(HexState.EMPTY)
            self.start_hex = None
            self.update_route()
        elif hex.state == HexState.END:
            hex.set_state(HexState.EMPTY)
            self.end_hex = None
            self.update_route()

    # Callback when debug visualisation is toggled
    def on_debug(self):
        self.debug = not self.debug
        for hex in self.hexes.values():
            hex.show_text(self.debug)

    # The distance between two hexes with the given axial coordinates
    def hex_distance(self, a, b):
        q1, r1 = a
        q2, r2 = b
        return (
            abs(q1 - q2)
            + abs(r1 - r2)
            + abs((q1 + r1) - (q2 + r2))
        ) // 2

    # Estimated cost from the given hex to the end hex
    def compute_h(self, hex):
        return self.hex_distance(hex.axial_coord, self.end_hex.axial_coord)

    # Find the (up to) six neighbours of the given hex
    def find_neighbours(self, hex):
        q, r = hex.axial_coord
        neighbours = []
        for n in range(6):
            dq, dr = HEX_DIRECTIONS[n]
            neighbour_axial_coord = (q + dq, r + dr)
            if neighbour_axial_coord in self.hexes:
                hex = self.hexes[neighbour_axial_coord]
                if hex.state != HexState.BARRIER:
                    neighbours.append(hex)
        return neighbours

    # Reconstruct the route generated by the A* algorithm
    def reconstruct_route(self, current, came_from):
        route = [current]
        while current in came_from:
            current = came_from[current]
            route.append(current)
        route.reverse()
        return route

    # The A* algorithm
    # https://en.wikipedia.org/wiki/A*_search_algorithm
    # This was implemented from pseudocode generated by ChatGPT
    def a_star(self):
        # Allow the final route to be constructed
        came_from = {}

        # The open set contains hexes A* is currently examining
        open_set = [self.start_hex]

        # The closed set contains hexes A* has finished examining
        closed_set = []

        # The g value of a hex is best current cost from the start to the hex
        # via the route currently being examined
        g = {}
        g[self.start_hex] = 0

        # The h value of a hex is the cost from the hex to the end
        h = {}
        h[self.start_hex] = self.compute_h(self.start_hex)

        # The f value for a hex is the sum of g and h
        f = {}
        f[self.start_hex] = h[self.start_hex]

        while open_set:
            # Get the hex with the best value of f
            current = min(open_set, key=lambda node: f[node])

            # Check to see if we have reached the end
            if current == self.end_hex:
                for hex in self.hexes.values():
                    if hex in f and hex in g and hex in h:
                        hex.set_text(f"{f[hex]}={g[hex]}+{h[hex]}")
                return self.reconstruct_route(current, came_from)

            # We have finished examining the current hex
            open_set.remove(current)
            closed_set.append(current)

            # Look at all the neighbours of the current hex
            neighbours = self.find_neighbours(current)
            for neighbour in neighbours:
                # Check to see if we have finished examining the neighbour hex
                if neighbour in closed_set:
                    continue

                # A neighbour hex is increases the g cost by 1 as it is one hex further
                tentative_g = g[current] + 1

                # Check if we want to examine the neighbour hex later
                if not neighbour in open_set:
                    open_set.append(neighbour)
                elif tentative_g >= g[neighbour]:
                    # The g cost of this route is worse than the existing route
                    continue

                # Update the f = g + h values for the hex
                came_from[neighbour] = current
                g[neighbour] = tentative_g
                h[neighbour] = self.compute_h(neighbour)
                f[neighbour] = g[neighbour] + h[neighbour]

        return []
