from hex import HexState, Hex

# A hex has six neighbours given as offsets from a central axial coordinate
HEX_DIRECTIONS = [
    (1, 0),
    (1, -1),
    (0, -1),
    (-1, 0),
    (-1, 1),
    (0, 1),
]
# A 9x9 hex map extends 4 hexes out from an origin hex
HEX_RANGE = 4


# A hex map is a contiguous arrangement of connected hexes
class Map:
    # Create the hex map
    def __init__(self, canvas):
        self.canvas = canvas
        # The start and end hexes for a potential route through the hex map
        self.start_hex = None
        self.end_hex = None
        self.hexes = {}
        # Create the hexes in the hex map. Nudge the hexes so they form a rough square
        for r in range(-HEX_RANGE, HEX_RANGE + 1):
            for q in range(-HEX_RANGE, HEX_RANGE + 1):
                axial_coord = (q + -(r // 2), r)
                self.hexes[axial_coord] = Hex(
                    canvas, axial_coord, self.on_start, self.on_end, self.on_clear, self.on_barrier)

    # Calculate the route through the hex map
    def update_route(self):
        # Wipe the previously drawn route
        for hex in self.hexes.values():
            if hex.state == HexState.EMPTY:
                hex.set_colour_from_state()
        # Calculate the route and indicate it on the hex map
        if self.start_hex and self.end_hex:
            route = self.a_star()
            for hex in route:
                if not hex == self.start_hex and not hex == self.end_hex:
                    self.canvas.itemconfig(hex.polygon, fill="orange")

    # Callback when a barrier in the hex map is changed
    def on_barrier(self):
        self.update_route()

    # Callback when the start hex in the hex map is changed
    def on_start(self, hex):
        if hex.state == HexState.EMPTY:
            if self.start_hex:
                self.start_hex.set_state(HexState.EMPTY)
            hex.set_state(HexState.START)
            self.start_hex = hex
            self.update_route()

    # Callback when the end hex is the hex map is changed
    def on_end(self, hex):
        if hex.state == HexState.EMPTY:
            if self.end_hex:
                self.end_hex.set_state(HexState.EMPTY)
            hex.set_state(HexState.END)
            self.end_hex = hex
            self.update_route()

    # Callback when either the start or end hex is cleared
    def on_clear(self, hex):
        if hex.state == HexState.START:
            hex.set_state(HexState.EMPTY)
            self.start_hex = None
            self.update_route()
        elif hex.state == HexState.END:
            hex.set_state(HexState.EMPTY)
            self.end_hex = None
            self.update_route()

    # The distance between two hexes with the given axial coordinates
    def hex_distance(self, a, b):
        q1, r1 = a
        q2, r2 = b
        return (
            abs(q1 - q2)
            + abs(r1 - r2)
            + abs((q1 + r1) - (q2 + r2))
        )

    # Cost from the start hex to the given hex
    def compute_g(self, hex):
        return self.hex_distance(self.start_hex.axial_coord, hex.axial_coord)

    # Estimated cost from the given hex to the end hex
    def compute_h(self, hex):
        return self.hex_distance(hex.axial_coord, self.end_hex.axial_coord)

    # Find the (up to) six neighbours of the given hex
    def find_neighbours(self, hex):
        q, r = hex.axial_coord
        neighbours = []
        for n in range(6):
            dq, dr = HEX_DIRECTIONS[n]
            neighbour_axial_coord = (q + dq, r + dr)
            if neighbour_axial_coord in self.hexes:
                hex = self.hexes[neighbour_axial_coord]
                if hex.state != HexState.BARRIER:
                    neighbours.append(hex)
        return neighbours

    # Reconstruct the route generated by the A* algorithm
    def reconstruct_route(self, current, came_from):
        route = [current]
        while current in came_from:
            current = came_from[current]
            route.append(current)
        route.reverse()
        return route

    # The A* algorithm
    # https://en.wikipedia.org/wiki/A*_search_algorithm
    # This was implemented from pseudocode generated by ChatGPT
    def a_star(self):
        came_from = {}

        open_set = [self.start_hex]
        closed_set = []
        g = {}
        g[self.start_hex] = 0
        f = {}
        f[self.start_hex] = self.compute_h(self.start_hex)

        while open_set:
            current = min(open_set, key=lambda node: f[node])

            if current == self.end_hex:
                return self.reconstruct_route(current, came_from)

            open_set.remove(current)
            closed_set.append(current)

            neighbours = self.find_neighbours(current)
            for neighbour in neighbours:
                if neighbour in closed_set:
                    continue

                tentative_g = g[current] + 1

                if not neighbour in open_set:
                    open_set.append(neighbour)
                elif tentative_g >= g[neighbour]:
                    continue

                came_from[neighbour] = current
                g[neighbour] = tentative_g
                f[neighbour] = g[neighbour] + self.compute_h(neighbour)

        return []
